### PR TITLE
Contextual errors, and refactor functions in handler

### LINKED ISSUE #77: Better error localization and informative error messages
In the existing version of the app, we don't care about the exact field or set of fields that are causing the error.

For instance, in the case of a duplicate contest name passed at the time of contest creation, we simply get "Contest could not be created", without any other details as to why. Please look at the screenshot below:
image

A partial fix is to the pass the error string to the front-end, but for people with no domain knowledge, this is not good. Please look below:
image

I propose that we invoke field errors (presented in #76 for date checking). Please look below.
image

If this proposal is cool, I'll point out places where the code will have to be changed.

cc: @prateekkumarweb @vbsinha

### PR DESCRIPTION
**Pull request by vishwakftw**
Closes #77

### CODE REVIEW

**Comment by vishwakftw** [comment]
@vbsinha: Please review handler changes. It's a huge diff, so take your time.

**Comment by vishwakftw** [comment]
I still have to fix the linking to views.py

**Comment by vishwakftw** [comment]
Actually, wait. I'll fix the merge conflicts.

**Comment by vishwakftw** [comment]
@vbsinha: should be good to review now

**Comment by vishwakftw** [comment]
I locally checked if the site works, and yes it does.

**Comment by vbsinha** [comment]
Woah! This was a HUGE update! Thanks, @vishwakftw.

I have gone over the code. I think it's all right. However, the best way would be to test it out.

**Comment by vishwakftw** [comment]
Merging, coz I’ve already tested it.

**Pull request merged**
