### PR TITLE
Add support for more languages

### PR DESCRIPTION
**Pull request by vishwakftw**
I'd like to support as many languages as possible from this list.

https://www.hackerrank.com/environment

Too ambitious maybe.

### CODE REVIEW

**Comment by vbsinha** [comment]
Good idea. I believe you've added support for Java and Go. Perhaps we can also add for Eiffel. This is because Saurabh sir is gonna use it eventually, better we do it before hand. Give him more reason to use this.

**Comment by vbsinha** [comment]
What is our C++ standard, 14? Also please check the libraries that hackerrank links to the languages. `-lm` for C++, C and `strings, math, container/heap, container/list` for Go might be useful for us.

**Comment by vishwakftw** [comment]
Yep, I’ll check the exact specs

**Comment by vishwakftw** [comment]
I'm testing manually to see if the image gets built successfully.

**Comment by vbsinha** [comment]
One thing. We might need to reflect these new languages in our backend and frontend. We can handle that in another PR.

**Comment by vishwakftw** [comment]
Its done

**Comment by vishwakftw** [comment]
Check forms.py and models.py in this diff.

**Comment by vbsinha** [comment]
Yeah. Sorry my bad.

**Pull request merged**
